"""add equipment requests table

Revision ID: 6033edb7cf56
Revises: d9d55063ee27
Create Date: 2026-02-14 13:54:03.021987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6033edb7cf56'
down_revision: Union[str, Sequence[str], None] = 'd9d55063ee27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('requested_by', sa.String(length=120), nullable=False),
    sa.Column('justification', sa.Text(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='equipment_request_status_enum', native_enum=False), server_default='pending', nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_requests_equipment_id'), 'equipment_requests', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_equipment_requests_id'), 'equipment_requests', ['id'], unique=False)
    op.create_index(op.f('ix_equipment_requests_organization_id'), 'equipment_requests', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_equipment_requests_organization_id'), table_name='equipment_requests')
    op.drop_index(op.f('ix_equipment_requests_id'), table_name='equipment_requests')
    op.drop_index(op.f('ix_equipment_requests_equipment_id'), table_name='equipment_requests')
    op.drop_table('equipment_requests')
    # ### end Alembic commands ###
